// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file traderState.proto (package treasury, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file traderState.proto.
 */
export const file_traderState: GenFile = /*@__PURE__*/
  fileDesc("ChF0cmFkZXJTdGF0ZS5wcm90bxIIdHJlYXN1cnkiHQoLVHJhZGVyU3RhdGUSDgoGYWN0aXZlGAEgASgIQksKNGNvbS5sdWNlcmEubHVtZW1hcmtldHMucHJvdG9idWYudHJlYXN1cnkudHJhZGVyc3RhdGVCEVRyYWRlclN0YXRlUHJvdG9zUAFiBnByb3RvMw");

/**
 * @generated from message treasury.TraderState
 */
export type TraderState = Message<"treasury.TraderState"> & {
  /**
   * @generated from field: bool active = 1;
   */
  active: boolean;
};

/**
 * Describes the message treasury.TraderState.
 * Use `create(TraderStateSchema)` to create a new message.
 */
export const TraderStateSchema: GenMessage<TraderState> = /*@__PURE__*/
  messageDesc(file_traderState, 0);

