// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/inquiry.proto
// Protobuf Java Version: 4.28.1

package com.lucera.lumemarkets.protobuf.treasury.inquiry;

public interface InquiryDateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:treasury.InquiryDate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 year = 1;</code>
   * @return The year.
   */
  int getYear();

  /**
   * <code>int32 month = 2;</code>
   * @return The month.
   */
  int getMonth();

  /**
   * <code>int32 day = 3;</code>
   * @return The day.
   */
  int getDay();
}
