// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/inquiry.proto
// Protobuf Java Version: 4.28.1

package com.lucera.lumemarkets.protobuf.treasury.inquiry;

/**
 * Protobuf enum {@code treasury.InquiryType}
 */
public enum InquiryType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ORDER_PROPOSAL = 0;</code>
   */
  ORDER_PROPOSAL(0),
  /**
   * <code>REGULAR_QUOTE_REQUEST = 1;</code>
   */
  REGULAR_QUOTE_REQUEST(1),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 1,
      /* suffix= */ "",
      InquiryType.class.getName());
  }
  /**
   * <code>ORDER_PROPOSAL = 0;</code>
   */
  public static final int ORDER_PROPOSAL_VALUE = 0;
  /**
   * <code>REGULAR_QUOTE_REQUEST = 1;</code>
   */
  public static final int REGULAR_QUOTE_REQUEST_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static InquiryType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static InquiryType forNumber(int value) {
    switch (value) {
      case 0: return ORDER_PROPOSAL;
      case 1: return REGULAR_QUOTE_REQUEST;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<InquiryType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      InquiryType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<InquiryType>() {
          public InquiryType findValueByNumber(int number) {
            return InquiryType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.lucera.lumemarkets.protobuf.treasury.inquiry.InquiryProtos.getDescriptor().getEnumTypes().get(0);
  }

  private static final InquiryType[] VALUES = values();

  public static InquiryType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private InquiryType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:treasury.InquiryType)
}

