// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/inquiry.proto
// Protobuf Java Version: 4.28.1

package com.lucera.lumemarkets.protobuf.treasury.inquiry;

public interface InquiryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:treasury.Inquiry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string tier = 2;</code>
   * @return The tier.
   */
  java.lang.String getTier();
  /**
   * <code>string tier = 2;</code>
   * @return The bytes for tier.
   */
  com.google.protobuf.ByteString
      getTierBytes();

  /**
   * <code>.treasury.InquiryType type = 3;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.treasury.InquiryType type = 3;</code>
   * @return The type.
   */
  com.lucera.lumemarkets.protobuf.treasury.inquiry.InquiryType getType();

  /**
   * <code>repeated string primaryCoveringTraders = 4;</code>
   * @return A list containing the primaryCoveringTraders.
   */
  java.util.List<java.lang.String>
      getPrimaryCoveringTradersList();
  /**
   * <code>repeated string primaryCoveringTraders = 4;</code>
   * @return The count of primaryCoveringTraders.
   */
  int getPrimaryCoveringTradersCount();
  /**
   * <code>repeated string primaryCoveringTraders = 4;</code>
   * @param index The index of the element to return.
   * @return The primaryCoveringTraders at the given index.
   */
  java.lang.String getPrimaryCoveringTraders(int index);
  /**
   * <code>repeated string primaryCoveringTraders = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the primaryCoveringTraders at the given index.
   */
  com.google.protobuf.ByteString
      getPrimaryCoveringTradersBytes(int index);

  /**
   * <code>repeated string secondaryCoveringTraders = 5;</code>
   * @return A list containing the secondaryCoveringTraders.
   */
  java.util.List<java.lang.String>
      getSecondaryCoveringTradersList();
  /**
   * <code>repeated string secondaryCoveringTraders = 5;</code>
   * @return The count of secondaryCoveringTraders.
   */
  int getSecondaryCoveringTradersCount();
  /**
   * <code>repeated string secondaryCoveringTraders = 5;</code>
   * @param index The index of the element to return.
   * @return The secondaryCoveringTraders at the given index.
   */
  java.lang.String getSecondaryCoveringTraders(int index);
  /**
   * <code>repeated string secondaryCoveringTraders = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the secondaryCoveringTraders at the given index.
   */
  com.google.protobuf.ByteString
      getSecondaryCoveringTradersBytes(int index);

  /**
   * <code>int32 numberOfDealers = 6;</code>
   * @return The numberOfDealers.
   */
  int getNumberOfDealers();

  /**
   * <code>bool isActive = 7;</code>
   * @return The isActive.
   */
  boolean getIsActive();

  /**
   * <code>bool showInquiryPopup = 8;</code>
   * @return The showInquiryPopup.
   */
  boolean getShowInquiryPopup();

  /**
   * <code>string title = 9;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 9;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string clientAccount = 10;</code>
   * @return The clientAccount.
   */
  java.lang.String getClientAccount();
  /**
   * <code>string clientAccount = 10;</code>
   * @return The bytes for clientAccount.
   */
  com.google.protobuf.ByteString
      getClientAccountBytes();

  /**
   * <code>string clientID = 11;</code>
   * @return The clientID.
   */
  java.lang.String getClientID();
  /**
   * <code>string clientID = 11;</code>
   * @return The bytes for clientID.
   */
  com.google.protobuf.ByteString
      getClientIDBytes();

  /**
   * <code>string clientName = 12;</code>
   * @return The clientName.
   */
  java.lang.String getClientName();
  /**
   * <code>string clientName = 12;</code>
   * @return The bytes for clientName.
   */
  com.google.protobuf.ByteString
      getClientNameBytes();

  /**
   * <code>string contact = 13;</code>
   * @return The contact.
   */
  java.lang.String getContact();
  /**
   * <code>string contact = 13;</code>
   * @return The bytes for contact.
   */
  com.google.protobuf.ByteString
      getContactBytes();

  /**
   * <code>string salesPerson = 14;</code>
   * @return The salesPerson.
   */
  java.lang.String getSalesPerson();
  /**
   * <code>string salesPerson = 14;</code>
   * @return The bytes for salesPerson.
   */
  com.google.protobuf.ByteString
      getSalesPersonBytes();

  /**
   * <code>int32 wireTime = 15;</code>
   * @return The wireTime.
   */
  int getWireTime();

  /**
   * <code>int32 wiretimeExpiration = 16;</code>
   * @return The wiretimeExpiration.
   */
  int getWiretimeExpiration();

  /**
   * <code>int32 coverSpread = 17;</code>
   * @return The coverSpread.
   */
  int getCoverSpread();

  /**
   * <code>int32 spread = 18;</code>
   * @return The spread.
   */
  int getSpread();

  /**
   * <code>repeated .treasury.Leg legs = 19;</code>
   */
  java.util.List<com.lucera.lumemarkets.protobuf.treasury.inquiry.Leg> 
      getLegsList();
  /**
   * <code>repeated .treasury.Leg legs = 19;</code>
   */
  com.lucera.lumemarkets.protobuf.treasury.inquiry.Leg getLegs(int index);
  /**
   * <code>repeated .treasury.Leg legs = 19;</code>
   */
  int getLegsCount();
  /**
   * <code>repeated .treasury.Leg legs = 19;</code>
   */
  java.util.List<? extends com.lucera.lumemarkets.protobuf.treasury.inquiry.LegOrBuilder> 
      getLegsOrBuilderList();
  /**
   * <code>repeated .treasury.Leg legs = 19;</code>
   */
  com.lucera.lumemarkets.protobuf.treasury.inquiry.LegOrBuilder getLegsOrBuilder(
      int index);

  /**
   * <code>string status = 20;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 20;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string venue = 21;</code>
   * @return The venue.
   */
  java.lang.String getVenue();
  /**
   * <code>string venue = 21;</code>
   * @return The bytes for venue.
   */
  com.google.protobuf.ByteString
      getVenueBytes();

  /**
   * <code>int32 transactTime = 22;</code>
   * @return The transactTime.
   */
  int getTransactTime();

  /**
   * <code>int32 expireTime = 23;</code>
   * @return The expireTime.
   */
  int getExpireTime();

  /**
   * <code>int32 hitLiftExpiration = 24;</code>
   * @return The hitLiftExpiration.
   */
  int getHitLiftExpiration();

  /**
   * <code>int32 quotedCount = 25;</code>
   * @return The quotedCount.
   */
  int getQuotedCount();

  /**
   * <code>string autoQuoteStatus = 26;</code>
   * @return The autoQuoteStatus.
   */
  java.lang.String getAutoQuoteStatus();
  /**
   * <code>string autoQuoteStatus = 26;</code>
   * @return The bytes for autoQuoteStatus.
   */
  com.google.protobuf.ByteString
      getAutoQuoteStatusBytes();

  /**
   * <code>string actingTraderId = 27;</code>
   * @return The actingTraderId.
   */
  java.lang.String getActingTraderId();
  /**
   * <code>string actingTraderId = 27;</code>
   * @return The bytes for actingTraderId.
   */
  com.google.protobuf.ByteString
      getActingTraderIdBytes();

  /**
   * <code>bool autoRejected = 28;</code>
   * @return The autoRejected.
   */
  boolean getAutoRejected();

  /**
   * <code>string autoRejectReason = 29;</code>
   * @return The autoRejectReason.
   */
  java.lang.String getAutoRejectReason();
  /**
   * <code>string autoRejectReason = 29;</code>
   * @return The bytes for autoRejectReason.
   */
  com.google.protobuf.ByteString
      getAutoRejectReasonBytes();

  /**
   * <code>string errorReason = 30;</code>
   * @return The errorReason.
   */
  java.lang.String getErrorReason();
  /**
   * <code>string errorReason = 30;</code>
   * @return The bytes for errorReason.
   */
  com.google.protobuf.ByteString
      getErrorReasonBytes();

  /**
   * <pre>
   * Updated field
   * </pre>
   *
   * <code>.treasury.InquiryDate settlement = 31;</code>
   * @return Whether the settlement field is set.
   */
  boolean hasSettlement();
  /**
   * <pre>
   * Updated field
   * </pre>
   *
   * <code>.treasury.InquiryDate settlement = 31;</code>
   * @return The settlement.
   */
  com.lucera.lumemarkets.protobuf.treasury.inquiry.InquiryDate getSettlement();
  /**
   * <pre>
   * Updated field
   * </pre>
   *
   * <code>.treasury.InquiryDate settlement = 31;</code>
   */
  com.lucera.lumemarkets.protobuf.treasury.inquiry.InquiryDateOrBuilder getSettlementOrBuilder();
}
