// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/inquiry.proto
// Protobuf Java Version: 4.28.1

package com.lucera.lumemarkets.protobuf.treasury.inquiry;

public interface MarketDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:treasury.MarketData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 mapxBidPrice = 1;</code>
   * @return The mapxBidPrice.
   */
  int getMapxBidPrice();

  /**
   * <code>int32 mapxBidYield = 2;</code>
   * @return The mapxBidYield.
   */
  int getMapxBidYield();

  /**
   * <code>int32 mapxOfferPrice = 3;</code>
   * @return The mapxOfferPrice.
   */
  int getMapxOfferPrice();

  /**
   * <code>int32 mapxOfferYield = 4;</code>
   * @return The mapxOfferYield.
   */
  int getMapxOfferYield();

  /**
   * <code>int32 twebBidPrice = 5;</code>
   * @return The twebBidPrice.
   */
  int getTwebBidPrice();

  /**
   * <code>int32 twebBidYield = 6;</code>
   * @return The twebBidYield.
   */
  int getTwebBidYield();

  /**
   * <code>int32 twebOfferPrice = 7;</code>
   * @return The twebOfferPrice.
   */
  int getTwebOfferPrice();

  /**
   * <code>int32 twebOfferYield = 8;</code>
   * @return The twebOfferYield.
   */
  int getTwebOfferYield();
}
