// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/inquiry.proto
// Protobuf Java Version: 4.28.1

package com.lucera.lume.protobuf.treasury.inquiry;

public final class InquiryProtos {
  private InquiryProtos() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 1,
      /* suffix= */ "",
      InquiryProtos.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_treasury_Inquiry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_treasury_Inquiry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_treasury_Leg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_treasury_Leg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_treasury_InquiryDate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_treasury_InquiryDate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_treasury_MarketData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_treasury_MarketData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023proto/inquiry.proto\022\010treasury\"\313\005\n\007Inqu" +
      "iry\022\n\n\002id\030\001 \001(\t\022\014\n\004tier\030\002 \001(\t\022#\n\004type\030\003 " +
      "\001(\0162\025.treasury.InquiryType\022\036\n\026primaryCov" +
      "eringTraders\030\004 \003(\t\022 \n\030secondaryCoveringT" +
      "raders\030\005 \003(\t\022\027\n\017numberOfDealers\030\006 \001(\005\022\020\n" +
      "\010isActive\030\007 \001(\010\022\030\n\020showInquiryPopup\030\010 \001(" +
      "\010\022\r\n\005title\030\t \001(\t\022\025\n\rclientAccount\030\n \001(\t\022" +
      "\020\n\010clientID\030\013 \001(\t\022\022\n\nclientName\030\014 \001(\t\022\017\n" +
      "\007contact\030\r \001(\t\022\023\n\013salesPerson\030\016 \001(\t\022\020\n\010w" +
      "ireTime\030\017 \001(\005\022\032\n\022wiretimeExpiration\030\020 \001(" +
      "\005\022\023\n\013coverSpread\030\021 \001(\005\022\016\n\006spread\030\022 \001(\005\022\033" +
      "\n\004legs\030\023 \003(\0132\r.treasury.Leg\022\016\n\006status\030\024 " +
      "\001(\t\022\r\n\005venue\030\025 \001(\t\022\024\n\014transactTime\030\026 \001(\005" +
      "\022\022\n\nexpireTime\030\027 \001(\005\022\031\n\021hitLiftExpiratio" +
      "n\030\030 \001(\005\022\023\n\013quotedCount\030\031 \001(\005\022\027\n\017autoQuot" +
      "eStatus\030\032 \001(\t\022\026\n\016actingTraderId\030\033 \001(\t\022\024\n" +
      "\014autoRejected\030\034 \001(\010\022\030\n\020autoRejectReason\030" +
      "\035 \001(\t\022\023\n\013errorReason\030\036 \001(\t\022)\n\nsettlement" +
      "\030\037 \001(\0132\025.treasury.InquiryDate\"\211\004\n\003Leg\022\r\n" +
      "\005legId\030\001 \001(\t\022\022\n\nisUnlocked\030\002 \001(\010\022\034\n\004side" +
      "\030\003 \001(\0162\016.treasury.Side\022\020\n\010quantity\030\004 \001(\005" +
      "\022\024\n\014instrumentId\030\005 \001(\t\022\024\n\014marketSymbol\030\006" +
      " \001(\t\022)\n\nsettlement\030\007 \001(\0132\025.treasury.Inqu" +
      "iryDate\022\r\n\005price\030\010 \001(\005\022\025\n\roriginalPrice\030" +
      "\t \001(\005\022\r\n\005cover\030\n \001(\005\022\r\n\005yield\030\013 \001(\005\022\020\n\010p" +
      "osition\030\014 \001(\005\022\034\n\024numberOfDaysToSettle\030\r " +
      "\001(\005\022\032\n\022standardSettleDate\030\016 \001(\010\022\014\n\004risk\030" +
      "\017 \001(\005\022\020\n\010repoRate\030\020 \001(\005\022\030\n\020originalRepoR" +
      "ate\030\021 \001(\005\022\025\n\rrepoRatePrice\030\022 \001(\005\022\020\n\010sect" +
      "orId\030\023 \001(\t\022\035\n\025originalRepoRatePrice\030\024 \001(" +
      "\005\022\034\n\024repoUpdatedTimestamp\030\025 \001(\005\022(\n\nmarke" +
      "tData\030\026 \001(\0132\024.treasury.MarketData\"7\n\013Inq" +
      "uiryDate\022\014\n\004year\030\001 \001(\005\022\r\n\005month\030\002 \001(\005\022\013\n" +
      "\003day\030\003 \001(\005\"\304\001\n\nMarketData\022\024\n\014mapxBidPric" +
      "e\030\001 \001(\005\022\024\n\014mapxBidYield\030\002 \001(\005\022\026\n\016mapxOff" +
      "erPrice\030\003 \001(\005\022\026\n\016mapxOfferYield\030\004 \001(\005\022\024\n" +
      "\014twebBidPrice\030\005 \001(\005\022\024\n\014twebBidYield\030\006 \001(" +
      "\005\022\026\n\016twebOfferPrice\030\007 \001(\005\022\026\n\016twebOfferYi" +
      "eld\030\010 \001(\005*<\n\013InquiryType\022\022\n\016ORDER_PROPOS" +
      "AL\020\000\022\031\n\025REGULAR_QUOTE_REQUEST\020\001*\031\n\004Side\022" +
      "\010\n\004SELL\020\000\022\007\n\003BUY\020\001B<\n)com.lucera.lume.pr" +
      "otobuf.treasury.inquiryB\rInquiryProtosP\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_treasury_Inquiry_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_treasury_Inquiry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_treasury_Inquiry_descriptor,
        new java.lang.String[] { "Id", "Tier", "Type", "PrimaryCoveringTraders", "SecondaryCoveringTraders", "NumberOfDealers", "IsActive", "ShowInquiryPopup", "Title", "ClientAccount", "ClientID", "ClientName", "Contact", "SalesPerson", "WireTime", "WiretimeExpiration", "CoverSpread", "Spread", "Legs", "Status", "Venue", "TransactTime", "ExpireTime", "HitLiftExpiration", "QuotedCount", "AutoQuoteStatus", "ActingTraderId", "AutoRejected", "AutoRejectReason", "ErrorReason", "Settlement", });
    internal_static_treasury_Leg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_treasury_Leg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_treasury_Leg_descriptor,
        new java.lang.String[] { "LegId", "IsUnlocked", "Side", "Quantity", "InstrumentId", "MarketSymbol", "Settlement", "Price", "OriginalPrice", "Cover", "Yield", "Position", "NumberOfDaysToSettle", "StandardSettleDate", "Risk", "RepoRate", "OriginalRepoRate", "RepoRatePrice", "SectorId", "OriginalRepoRatePrice", "RepoUpdatedTimestamp", "MarketData", });
    internal_static_treasury_InquiryDate_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_treasury_InquiryDate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_treasury_InquiryDate_descriptor,
        new java.lang.String[] { "Year", "Month", "Day", });
    internal_static_treasury_MarketData_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_treasury_MarketData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_treasury_MarketData_descriptor,
        new java.lang.String[] { "MapxBidPrice", "MapxBidYield", "MapxOfferPrice", "MapxOfferYield", "TwebBidPrice", "TwebBidYield", "TwebOfferPrice", "TwebOfferYield", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
