// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/inquiry.proto
// Protobuf Java Version: 4.28.1

package com.lucera.lume.protobuf.treasury.inquiry;

/**
 * Protobuf type {@code treasury.Leg}
 */
public final class Leg extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:treasury.Leg)
    LegOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 1,
      /* suffix= */ "",
      Leg.class.getName());
  }
  // Use Leg.newBuilder() to construct.
  private Leg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Leg() {
    legId_ = "";
    side_ = 0;
    instrumentId_ = "";
    marketSymbol_ = "";
    sectorId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lucera.lume.protobuf.treasury.inquiry.InquiryProtos.internal_static_treasury_Leg_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lucera.lume.protobuf.treasury.inquiry.InquiryProtos.internal_static_treasury_Leg_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lucera.lume.protobuf.treasury.inquiry.Leg.class, com.lucera.lume.protobuf.treasury.inquiry.Leg.Builder.class);
  }

  private int bitField0_;
  public static final int LEGID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object legId_ = "";
  /**
   * <code>string legId = 1;</code>
   * @return The legId.
   */
  @java.lang.Override
  public java.lang.String getLegId() {
    java.lang.Object ref = legId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      legId_ = s;
      return s;
    }
  }
  /**
   * <code>string legId = 1;</code>
   * @return The bytes for legId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLegIdBytes() {
    java.lang.Object ref = legId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      legId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISUNLOCKED_FIELD_NUMBER = 2;
  private boolean isUnlocked_ = false;
  /**
   * <code>bool isUnlocked = 2;</code>
   * @return The isUnlocked.
   */
  @java.lang.Override
  public boolean getIsUnlocked() {
    return isUnlocked_;
  }

  public static final int SIDE_FIELD_NUMBER = 3;
  private int side_ = 0;
  /**
   * <code>.treasury.Side side = 3;</code>
   * @return The enum numeric value on the wire for side.
   */
  @java.lang.Override public int getSideValue() {
    return side_;
  }
  /**
   * <code>.treasury.Side side = 3;</code>
   * @return The side.
   */
  @java.lang.Override public com.lucera.lume.protobuf.treasury.inquiry.Side getSide() {
    com.lucera.lume.protobuf.treasury.inquiry.Side result = com.lucera.lume.protobuf.treasury.inquiry.Side.forNumber(side_);
    return result == null ? com.lucera.lume.protobuf.treasury.inquiry.Side.UNRECOGNIZED : result;
  }

  public static final int QUANTITY_FIELD_NUMBER = 4;
  private int quantity_ = 0;
  /**
   * <code>int32 quantity = 4;</code>
   * @return The quantity.
   */
  @java.lang.Override
  public int getQuantity() {
    return quantity_;
  }

  public static final int INSTRUMENTID_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object instrumentId_ = "";
  /**
   * <code>string instrumentId = 5;</code>
   * @return The instrumentId.
   */
  @java.lang.Override
  public java.lang.String getInstrumentId() {
    java.lang.Object ref = instrumentId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      instrumentId_ = s;
      return s;
    }
  }
  /**
   * <code>string instrumentId = 5;</code>
   * @return The bytes for instrumentId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInstrumentIdBytes() {
    java.lang.Object ref = instrumentId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      instrumentId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MARKETSYMBOL_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object marketSymbol_ = "";
  /**
   * <code>string marketSymbol = 6;</code>
   * @return The marketSymbol.
   */
  @java.lang.Override
  public java.lang.String getMarketSymbol() {
    java.lang.Object ref = marketSymbol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      marketSymbol_ = s;
      return s;
    }
  }
  /**
   * <code>string marketSymbol = 6;</code>
   * @return The bytes for marketSymbol.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMarketSymbolBytes() {
    java.lang.Object ref = marketSymbol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      marketSymbol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SETTLEMENT_FIELD_NUMBER = 7;
  private com.lucera.lume.protobuf.treasury.inquiry.InquiryDate settlement_;
  /**
   * <code>.treasury.InquiryDate settlement = 7;</code>
   * @return Whether the settlement field is set.
   */
  @java.lang.Override
  public boolean hasSettlement() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.treasury.InquiryDate settlement = 7;</code>
   * @return The settlement.
   */
  @java.lang.Override
  public com.lucera.lume.protobuf.treasury.inquiry.InquiryDate getSettlement() {
    return settlement_ == null ? com.lucera.lume.protobuf.treasury.inquiry.InquiryDate.getDefaultInstance() : settlement_;
  }
  /**
   * <code>.treasury.InquiryDate settlement = 7;</code>
   */
  @java.lang.Override
  public com.lucera.lume.protobuf.treasury.inquiry.InquiryDateOrBuilder getSettlementOrBuilder() {
    return settlement_ == null ? com.lucera.lume.protobuf.treasury.inquiry.InquiryDate.getDefaultInstance() : settlement_;
  }

  public static final int PRICE_FIELD_NUMBER = 8;
  private int price_ = 0;
  /**
   * <code>int32 price = 8;</code>
   * @return The price.
   */
  @java.lang.Override
  public int getPrice() {
    return price_;
  }

  public static final int ORIGINALPRICE_FIELD_NUMBER = 9;
  private int originalPrice_ = 0;
  /**
   * <code>int32 originalPrice = 9;</code>
   * @return The originalPrice.
   */
  @java.lang.Override
  public int getOriginalPrice() {
    return originalPrice_;
  }

  public static final int COVER_FIELD_NUMBER = 10;
  private int cover_ = 0;
  /**
   * <code>int32 cover = 10;</code>
   * @return The cover.
   */
  @java.lang.Override
  public int getCover() {
    return cover_;
  }

  public static final int YIELD_FIELD_NUMBER = 11;
  private int yield_ = 0;
  /**
   * <code>int32 yield = 11;</code>
   * @return The yield.
   */
  @java.lang.Override
  public int getYield() {
    return yield_;
  }

  public static final int POSITION_FIELD_NUMBER = 12;
  private int position_ = 0;
  /**
   * <code>int32 position = 12;</code>
   * @return The position.
   */
  @java.lang.Override
  public int getPosition() {
    return position_;
  }

  public static final int NUMBEROFDAYSTOSETTLE_FIELD_NUMBER = 13;
  private int numberOfDaysToSettle_ = 0;
  /**
   * <code>int32 numberOfDaysToSettle = 13;</code>
   * @return The numberOfDaysToSettle.
   */
  @java.lang.Override
  public int getNumberOfDaysToSettle() {
    return numberOfDaysToSettle_;
  }

  public static final int STANDARDSETTLEDATE_FIELD_NUMBER = 14;
  private boolean standardSettleDate_ = false;
  /**
   * <code>bool standardSettleDate = 14;</code>
   * @return The standardSettleDate.
   */
  @java.lang.Override
  public boolean getStandardSettleDate() {
    return standardSettleDate_;
  }

  public static final int RISK_FIELD_NUMBER = 15;
  private int risk_ = 0;
  /**
   * <code>int32 risk = 15;</code>
   * @return The risk.
   */
  @java.lang.Override
  public int getRisk() {
    return risk_;
  }

  public static final int REPORATE_FIELD_NUMBER = 16;
  private int repoRate_ = 0;
  /**
   * <pre>
   * Only included if the quote has a non-standard settle date
   * </pre>
   *
   * <code>int32 repoRate = 16;</code>
   * @return The repoRate.
   */
  @java.lang.Override
  public int getRepoRate() {
    return repoRate_;
  }

  public static final int ORIGINALREPORATE_FIELD_NUMBER = 17;
  private int originalRepoRate_ = 0;
  /**
   * <code>int32 originalRepoRate = 17;</code>
   * @return The originalRepoRate.
   */
  @java.lang.Override
  public int getOriginalRepoRate() {
    return originalRepoRate_;
  }

  public static final int REPORATEPRICE_FIELD_NUMBER = 18;
  private int repoRatePrice_ = 0;
  /**
   * <code>int32 repoRatePrice = 18;</code>
   * @return The repoRatePrice.
   */
  @java.lang.Override
  public int getRepoRatePrice() {
    return repoRatePrice_;
  }

  public static final int SECTORID_FIELD_NUMBER = 19;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sectorId_ = "";
  /**
   * <code>string sectorId = 19;</code>
   * @return The sectorId.
   */
  @java.lang.Override
  public java.lang.String getSectorId() {
    java.lang.Object ref = sectorId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sectorId_ = s;
      return s;
    }
  }
  /**
   * <code>string sectorId = 19;</code>
   * @return The bytes for sectorId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSectorIdBytes() {
    java.lang.Object ref = sectorId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sectorId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORIGINALREPORATEPRICE_FIELD_NUMBER = 20;
  private int originalRepoRatePrice_ = 0;
  /**
   * <code>int32 originalRepoRatePrice = 20;</code>
   * @return The originalRepoRatePrice.
   */
  @java.lang.Override
  public int getOriginalRepoRatePrice() {
    return originalRepoRatePrice_;
  }

  public static final int REPOUPDATEDTIMESTAMP_FIELD_NUMBER = 21;
  private int repoUpdatedTimestamp_ = 0;
  /**
   * <code>int32 repoUpdatedTimestamp = 21;</code>
   * @return The repoUpdatedTimestamp.
   */
  @java.lang.Override
  public int getRepoUpdatedTimestamp() {
    return repoUpdatedTimestamp_;
  }

  public static final int MARKETDATA_FIELD_NUMBER = 22;
  private com.lucera.lume.protobuf.treasury.inquiry.MarketData marketData_;
  /**
   * <code>.treasury.MarketData marketData = 22;</code>
   * @return Whether the marketData field is set.
   */
  @java.lang.Override
  public boolean hasMarketData() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.treasury.MarketData marketData = 22;</code>
   * @return The marketData.
   */
  @java.lang.Override
  public com.lucera.lume.protobuf.treasury.inquiry.MarketData getMarketData() {
    return marketData_ == null ? com.lucera.lume.protobuf.treasury.inquiry.MarketData.getDefaultInstance() : marketData_;
  }
  /**
   * <code>.treasury.MarketData marketData = 22;</code>
   */
  @java.lang.Override
  public com.lucera.lume.protobuf.treasury.inquiry.MarketDataOrBuilder getMarketDataOrBuilder() {
    return marketData_ == null ? com.lucera.lume.protobuf.treasury.inquiry.MarketData.getDefaultInstance() : marketData_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(legId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, legId_);
    }
    if (isUnlocked_ != false) {
      output.writeBool(2, isUnlocked_);
    }
    if (side_ != com.lucera.lume.protobuf.treasury.inquiry.Side.SELL.getNumber()) {
      output.writeEnum(3, side_);
    }
    if (quantity_ != 0) {
      output.writeInt32(4, quantity_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(instrumentId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, instrumentId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(marketSymbol_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, marketSymbol_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(7, getSettlement());
    }
    if (price_ != 0) {
      output.writeInt32(8, price_);
    }
    if (originalPrice_ != 0) {
      output.writeInt32(9, originalPrice_);
    }
    if (cover_ != 0) {
      output.writeInt32(10, cover_);
    }
    if (yield_ != 0) {
      output.writeInt32(11, yield_);
    }
    if (position_ != 0) {
      output.writeInt32(12, position_);
    }
    if (numberOfDaysToSettle_ != 0) {
      output.writeInt32(13, numberOfDaysToSettle_);
    }
    if (standardSettleDate_ != false) {
      output.writeBool(14, standardSettleDate_);
    }
    if (risk_ != 0) {
      output.writeInt32(15, risk_);
    }
    if (repoRate_ != 0) {
      output.writeInt32(16, repoRate_);
    }
    if (originalRepoRate_ != 0) {
      output.writeInt32(17, originalRepoRate_);
    }
    if (repoRatePrice_ != 0) {
      output.writeInt32(18, repoRatePrice_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sectorId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 19, sectorId_);
    }
    if (originalRepoRatePrice_ != 0) {
      output.writeInt32(20, originalRepoRatePrice_);
    }
    if (repoUpdatedTimestamp_ != 0) {
      output.writeInt32(21, repoUpdatedTimestamp_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(22, getMarketData());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(legId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, legId_);
    }
    if (isUnlocked_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, isUnlocked_);
    }
    if (side_ != com.lucera.lume.protobuf.treasury.inquiry.Side.SELL.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, side_);
    }
    if (quantity_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, quantity_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(instrumentId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, instrumentId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(marketSymbol_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, marketSymbol_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getSettlement());
    }
    if (price_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, price_);
    }
    if (originalPrice_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, originalPrice_);
    }
    if (cover_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, cover_);
    }
    if (yield_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, yield_);
    }
    if (position_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(12, position_);
    }
    if (numberOfDaysToSettle_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(13, numberOfDaysToSettle_);
    }
    if (standardSettleDate_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(14, standardSettleDate_);
    }
    if (risk_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(15, risk_);
    }
    if (repoRate_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(16, repoRate_);
    }
    if (originalRepoRate_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(17, originalRepoRate_);
    }
    if (repoRatePrice_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(18, repoRatePrice_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sectorId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(19, sectorId_);
    }
    if (originalRepoRatePrice_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(20, originalRepoRatePrice_);
    }
    if (repoUpdatedTimestamp_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(21, repoUpdatedTimestamp_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(22, getMarketData());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.lucera.lume.protobuf.treasury.inquiry.Leg)) {
      return super.equals(obj);
    }
    com.lucera.lume.protobuf.treasury.inquiry.Leg other = (com.lucera.lume.protobuf.treasury.inquiry.Leg) obj;

    if (!getLegId()
        .equals(other.getLegId())) return false;
    if (getIsUnlocked()
        != other.getIsUnlocked()) return false;
    if (side_ != other.side_) return false;
    if (getQuantity()
        != other.getQuantity()) return false;
    if (!getInstrumentId()
        .equals(other.getInstrumentId())) return false;
    if (!getMarketSymbol()
        .equals(other.getMarketSymbol())) return false;
    if (hasSettlement() != other.hasSettlement()) return false;
    if (hasSettlement()) {
      if (!getSettlement()
          .equals(other.getSettlement())) return false;
    }
    if (getPrice()
        != other.getPrice()) return false;
    if (getOriginalPrice()
        != other.getOriginalPrice()) return false;
    if (getCover()
        != other.getCover()) return false;
    if (getYield()
        != other.getYield()) return false;
    if (getPosition()
        != other.getPosition()) return false;
    if (getNumberOfDaysToSettle()
        != other.getNumberOfDaysToSettle()) return false;
    if (getStandardSettleDate()
        != other.getStandardSettleDate()) return false;
    if (getRisk()
        != other.getRisk()) return false;
    if (getRepoRate()
        != other.getRepoRate()) return false;
    if (getOriginalRepoRate()
        != other.getOriginalRepoRate()) return false;
    if (getRepoRatePrice()
        != other.getRepoRatePrice()) return false;
    if (!getSectorId()
        .equals(other.getSectorId())) return false;
    if (getOriginalRepoRatePrice()
        != other.getOriginalRepoRatePrice()) return false;
    if (getRepoUpdatedTimestamp()
        != other.getRepoUpdatedTimestamp()) return false;
    if (hasMarketData() != other.hasMarketData()) return false;
    if (hasMarketData()) {
      if (!getMarketData()
          .equals(other.getMarketData())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LEGID_FIELD_NUMBER;
    hash = (53 * hash) + getLegId().hashCode();
    hash = (37 * hash) + ISUNLOCKED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsUnlocked());
    hash = (37 * hash) + SIDE_FIELD_NUMBER;
    hash = (53 * hash) + side_;
    hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
    hash = (53 * hash) + getQuantity();
    hash = (37 * hash) + INSTRUMENTID_FIELD_NUMBER;
    hash = (53 * hash) + getInstrumentId().hashCode();
    hash = (37 * hash) + MARKETSYMBOL_FIELD_NUMBER;
    hash = (53 * hash) + getMarketSymbol().hashCode();
    if (hasSettlement()) {
      hash = (37 * hash) + SETTLEMENT_FIELD_NUMBER;
      hash = (53 * hash) + getSettlement().hashCode();
    }
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + getPrice();
    hash = (37 * hash) + ORIGINALPRICE_FIELD_NUMBER;
    hash = (53 * hash) + getOriginalPrice();
    hash = (37 * hash) + COVER_FIELD_NUMBER;
    hash = (53 * hash) + getCover();
    hash = (37 * hash) + YIELD_FIELD_NUMBER;
    hash = (53 * hash) + getYield();
    hash = (37 * hash) + POSITION_FIELD_NUMBER;
    hash = (53 * hash) + getPosition();
    hash = (37 * hash) + NUMBEROFDAYSTOSETTLE_FIELD_NUMBER;
    hash = (53 * hash) + getNumberOfDaysToSettle();
    hash = (37 * hash) + STANDARDSETTLEDATE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getStandardSettleDate());
    hash = (37 * hash) + RISK_FIELD_NUMBER;
    hash = (53 * hash) + getRisk();
    hash = (37 * hash) + REPORATE_FIELD_NUMBER;
    hash = (53 * hash) + getRepoRate();
    hash = (37 * hash) + ORIGINALREPORATE_FIELD_NUMBER;
    hash = (53 * hash) + getOriginalRepoRate();
    hash = (37 * hash) + REPORATEPRICE_FIELD_NUMBER;
    hash = (53 * hash) + getRepoRatePrice();
    hash = (37 * hash) + SECTORID_FIELD_NUMBER;
    hash = (53 * hash) + getSectorId().hashCode();
    hash = (37 * hash) + ORIGINALREPORATEPRICE_FIELD_NUMBER;
    hash = (53 * hash) + getOriginalRepoRatePrice();
    hash = (37 * hash) + REPOUPDATEDTIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + getRepoUpdatedTimestamp();
    if (hasMarketData()) {
      hash = (37 * hash) + MARKETDATA_FIELD_NUMBER;
      hash = (53 * hash) + getMarketData().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.lucera.lume.protobuf.treasury.inquiry.Leg parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lucera.lume.protobuf.treasury.inquiry.Leg parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lucera.lume.protobuf.treasury.inquiry.Leg parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lucera.lume.protobuf.treasury.inquiry.Leg parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lucera.lume.protobuf.treasury.inquiry.Leg parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lucera.lume.protobuf.treasury.inquiry.Leg parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lucera.lume.protobuf.treasury.inquiry.Leg parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.lucera.lume.protobuf.treasury.inquiry.Leg parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.lucera.lume.protobuf.treasury.inquiry.Leg parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.lucera.lume.protobuf.treasury.inquiry.Leg parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lucera.lume.protobuf.treasury.inquiry.Leg parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.lucera.lume.protobuf.treasury.inquiry.Leg parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lucera.lume.protobuf.treasury.inquiry.Leg prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code treasury.Leg}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:treasury.Leg)
      com.lucera.lume.protobuf.treasury.inquiry.LegOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lucera.lume.protobuf.treasury.inquiry.InquiryProtos.internal_static_treasury_Leg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lucera.lume.protobuf.treasury.inquiry.InquiryProtos.internal_static_treasury_Leg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lucera.lume.protobuf.treasury.inquiry.Leg.class, com.lucera.lume.protobuf.treasury.inquiry.Leg.Builder.class);
    }

    // Construct using com.lucera.lume.protobuf.treasury.inquiry.Leg.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getSettlementFieldBuilder();
        getMarketDataFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      legId_ = "";
      isUnlocked_ = false;
      side_ = 0;
      quantity_ = 0;
      instrumentId_ = "";
      marketSymbol_ = "";
      settlement_ = null;
      if (settlementBuilder_ != null) {
        settlementBuilder_.dispose();
        settlementBuilder_ = null;
      }
      price_ = 0;
      originalPrice_ = 0;
      cover_ = 0;
      yield_ = 0;
      position_ = 0;
      numberOfDaysToSettle_ = 0;
      standardSettleDate_ = false;
      risk_ = 0;
      repoRate_ = 0;
      originalRepoRate_ = 0;
      repoRatePrice_ = 0;
      sectorId_ = "";
      originalRepoRatePrice_ = 0;
      repoUpdatedTimestamp_ = 0;
      marketData_ = null;
      if (marketDataBuilder_ != null) {
        marketDataBuilder_.dispose();
        marketDataBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lucera.lume.protobuf.treasury.inquiry.InquiryProtos.internal_static_treasury_Leg_descriptor;
    }

    @java.lang.Override
    public com.lucera.lume.protobuf.treasury.inquiry.Leg getDefaultInstanceForType() {
      return com.lucera.lume.protobuf.treasury.inquiry.Leg.getDefaultInstance();
    }

    @java.lang.Override
    public com.lucera.lume.protobuf.treasury.inquiry.Leg build() {
      com.lucera.lume.protobuf.treasury.inquiry.Leg result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.lucera.lume.protobuf.treasury.inquiry.Leg buildPartial() {
      com.lucera.lume.protobuf.treasury.inquiry.Leg result = new com.lucera.lume.protobuf.treasury.inquiry.Leg(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.lucera.lume.protobuf.treasury.inquiry.Leg result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.legId_ = legId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.isUnlocked_ = isUnlocked_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.side_ = side_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.quantity_ = quantity_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.instrumentId_ = instrumentId_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.marketSymbol_ = marketSymbol_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.settlement_ = settlementBuilder_ == null
            ? settlement_
            : settlementBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.price_ = price_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.originalPrice_ = originalPrice_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.cover_ = cover_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.yield_ = yield_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.position_ = position_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.numberOfDaysToSettle_ = numberOfDaysToSettle_;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.standardSettleDate_ = standardSettleDate_;
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        result.risk_ = risk_;
      }
      if (((from_bitField0_ & 0x00008000) != 0)) {
        result.repoRate_ = repoRate_;
      }
      if (((from_bitField0_ & 0x00010000) != 0)) {
        result.originalRepoRate_ = originalRepoRate_;
      }
      if (((from_bitField0_ & 0x00020000) != 0)) {
        result.repoRatePrice_ = repoRatePrice_;
      }
      if (((from_bitField0_ & 0x00040000) != 0)) {
        result.sectorId_ = sectorId_;
      }
      if (((from_bitField0_ & 0x00080000) != 0)) {
        result.originalRepoRatePrice_ = originalRepoRatePrice_;
      }
      if (((from_bitField0_ & 0x00100000) != 0)) {
        result.repoUpdatedTimestamp_ = repoUpdatedTimestamp_;
      }
      if (((from_bitField0_ & 0x00200000) != 0)) {
        result.marketData_ = marketDataBuilder_ == null
            ? marketData_
            : marketDataBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lucera.lume.protobuf.treasury.inquiry.Leg) {
        return mergeFrom((com.lucera.lume.protobuf.treasury.inquiry.Leg)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lucera.lume.protobuf.treasury.inquiry.Leg other) {
      if (other == com.lucera.lume.protobuf.treasury.inquiry.Leg.getDefaultInstance()) return this;
      if (!other.getLegId().isEmpty()) {
        legId_ = other.legId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getIsUnlocked() != false) {
        setIsUnlocked(other.getIsUnlocked());
      }
      if (other.side_ != 0) {
        setSideValue(other.getSideValue());
      }
      if (other.getQuantity() != 0) {
        setQuantity(other.getQuantity());
      }
      if (!other.getInstrumentId().isEmpty()) {
        instrumentId_ = other.instrumentId_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getMarketSymbol().isEmpty()) {
        marketSymbol_ = other.marketSymbol_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.hasSettlement()) {
        mergeSettlement(other.getSettlement());
      }
      if (other.getPrice() != 0) {
        setPrice(other.getPrice());
      }
      if (other.getOriginalPrice() != 0) {
        setOriginalPrice(other.getOriginalPrice());
      }
      if (other.getCover() != 0) {
        setCover(other.getCover());
      }
      if (other.getYield() != 0) {
        setYield(other.getYield());
      }
      if (other.getPosition() != 0) {
        setPosition(other.getPosition());
      }
      if (other.getNumberOfDaysToSettle() != 0) {
        setNumberOfDaysToSettle(other.getNumberOfDaysToSettle());
      }
      if (other.getStandardSettleDate() != false) {
        setStandardSettleDate(other.getStandardSettleDate());
      }
      if (other.getRisk() != 0) {
        setRisk(other.getRisk());
      }
      if (other.getRepoRate() != 0) {
        setRepoRate(other.getRepoRate());
      }
      if (other.getOriginalRepoRate() != 0) {
        setOriginalRepoRate(other.getOriginalRepoRate());
      }
      if (other.getRepoRatePrice() != 0) {
        setRepoRatePrice(other.getRepoRatePrice());
      }
      if (!other.getSectorId().isEmpty()) {
        sectorId_ = other.sectorId_;
        bitField0_ |= 0x00040000;
        onChanged();
      }
      if (other.getOriginalRepoRatePrice() != 0) {
        setOriginalRepoRatePrice(other.getOriginalRepoRatePrice());
      }
      if (other.getRepoUpdatedTimestamp() != 0) {
        setRepoUpdatedTimestamp(other.getRepoUpdatedTimestamp());
      }
      if (other.hasMarketData()) {
        mergeMarketData(other.getMarketData());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              legId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              isUnlocked_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              side_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              quantity_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              instrumentId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              marketSymbol_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getSettlementFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 64: {
              price_ = input.readInt32();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              originalPrice_ = input.readInt32();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 80: {
              cover_ = input.readInt32();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            case 88: {
              yield_ = input.readInt32();
              bitField0_ |= 0x00000400;
              break;
            } // case 88
            case 96: {
              position_ = input.readInt32();
              bitField0_ |= 0x00000800;
              break;
            } // case 96
            case 104: {
              numberOfDaysToSettle_ = input.readInt32();
              bitField0_ |= 0x00001000;
              break;
            } // case 104
            case 112: {
              standardSettleDate_ = input.readBool();
              bitField0_ |= 0x00002000;
              break;
            } // case 112
            case 120: {
              risk_ = input.readInt32();
              bitField0_ |= 0x00004000;
              break;
            } // case 120
            case 128: {
              repoRate_ = input.readInt32();
              bitField0_ |= 0x00008000;
              break;
            } // case 128
            case 136: {
              originalRepoRate_ = input.readInt32();
              bitField0_ |= 0x00010000;
              break;
            } // case 136
            case 144: {
              repoRatePrice_ = input.readInt32();
              bitField0_ |= 0x00020000;
              break;
            } // case 144
            case 154: {
              sectorId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00040000;
              break;
            } // case 154
            case 160: {
              originalRepoRatePrice_ = input.readInt32();
              bitField0_ |= 0x00080000;
              break;
            } // case 160
            case 168: {
              repoUpdatedTimestamp_ = input.readInt32();
              bitField0_ |= 0x00100000;
              break;
            } // case 168
            case 178: {
              input.readMessage(
                  getMarketDataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00200000;
              break;
            } // case 178
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object legId_ = "";
    /**
     * <code>string legId = 1;</code>
     * @return The legId.
     */
    public java.lang.String getLegId() {
      java.lang.Object ref = legId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        legId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string legId = 1;</code>
     * @return The bytes for legId.
     */
    public com.google.protobuf.ByteString
        getLegIdBytes() {
      java.lang.Object ref = legId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        legId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string legId = 1;</code>
     * @param value The legId to set.
     * @return This builder for chaining.
     */
    public Builder setLegId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      legId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string legId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLegId() {
      legId_ = getDefaultInstance().getLegId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string legId = 1;</code>
     * @param value The bytes for legId to set.
     * @return This builder for chaining.
     */
    public Builder setLegIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      legId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private boolean isUnlocked_ ;
    /**
     * <code>bool isUnlocked = 2;</code>
     * @return The isUnlocked.
     */
    @java.lang.Override
    public boolean getIsUnlocked() {
      return isUnlocked_;
    }
    /**
     * <code>bool isUnlocked = 2;</code>
     * @param value The isUnlocked to set.
     * @return This builder for chaining.
     */
    public Builder setIsUnlocked(boolean value) {

      isUnlocked_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool isUnlocked = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsUnlocked() {
      bitField0_ = (bitField0_ & ~0x00000002);
      isUnlocked_ = false;
      onChanged();
      return this;
    }

    private int side_ = 0;
    /**
     * <code>.treasury.Side side = 3;</code>
     * @return The enum numeric value on the wire for side.
     */
    @java.lang.Override public int getSideValue() {
      return side_;
    }
    /**
     * <code>.treasury.Side side = 3;</code>
     * @param value The enum numeric value on the wire for side to set.
     * @return This builder for chaining.
     */
    public Builder setSideValue(int value) {
      side_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.treasury.Side side = 3;</code>
     * @return The side.
     */
    @java.lang.Override
    public com.lucera.lume.protobuf.treasury.inquiry.Side getSide() {
      com.lucera.lume.protobuf.treasury.inquiry.Side result = com.lucera.lume.protobuf.treasury.inquiry.Side.forNumber(side_);
      return result == null ? com.lucera.lume.protobuf.treasury.inquiry.Side.UNRECOGNIZED : result;
    }
    /**
     * <code>.treasury.Side side = 3;</code>
     * @param value The side to set.
     * @return This builder for chaining.
     */
    public Builder setSide(com.lucera.lume.protobuf.treasury.inquiry.Side value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      side_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.treasury.Side side = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSide() {
      bitField0_ = (bitField0_ & ~0x00000004);
      side_ = 0;
      onChanged();
      return this;
    }

    private int quantity_ ;
    /**
     * <code>int32 quantity = 4;</code>
     * @return The quantity.
     */
    @java.lang.Override
    public int getQuantity() {
      return quantity_;
    }
    /**
     * <code>int32 quantity = 4;</code>
     * @param value The quantity to set.
     * @return This builder for chaining.
     */
    public Builder setQuantity(int value) {

      quantity_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 quantity = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuantity() {
      bitField0_ = (bitField0_ & ~0x00000008);
      quantity_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object instrumentId_ = "";
    /**
     * <code>string instrumentId = 5;</code>
     * @return The instrumentId.
     */
    public java.lang.String getInstrumentId() {
      java.lang.Object ref = instrumentId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        instrumentId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string instrumentId = 5;</code>
     * @return The bytes for instrumentId.
     */
    public com.google.protobuf.ByteString
        getInstrumentIdBytes() {
      java.lang.Object ref = instrumentId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        instrumentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string instrumentId = 5;</code>
     * @param value The instrumentId to set.
     * @return This builder for chaining.
     */
    public Builder setInstrumentId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      instrumentId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string instrumentId = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearInstrumentId() {
      instrumentId_ = getDefaultInstance().getInstrumentId();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string instrumentId = 5;</code>
     * @param value The bytes for instrumentId to set.
     * @return This builder for chaining.
     */
    public Builder setInstrumentIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      instrumentId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object marketSymbol_ = "";
    /**
     * <code>string marketSymbol = 6;</code>
     * @return The marketSymbol.
     */
    public java.lang.String getMarketSymbol() {
      java.lang.Object ref = marketSymbol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        marketSymbol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string marketSymbol = 6;</code>
     * @return The bytes for marketSymbol.
     */
    public com.google.protobuf.ByteString
        getMarketSymbolBytes() {
      java.lang.Object ref = marketSymbol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        marketSymbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string marketSymbol = 6;</code>
     * @param value The marketSymbol to set.
     * @return This builder for chaining.
     */
    public Builder setMarketSymbol(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      marketSymbol_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string marketSymbol = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMarketSymbol() {
      marketSymbol_ = getDefaultInstance().getMarketSymbol();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string marketSymbol = 6;</code>
     * @param value The bytes for marketSymbol to set.
     * @return This builder for chaining.
     */
    public Builder setMarketSymbolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      marketSymbol_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private com.lucera.lume.protobuf.treasury.inquiry.InquiryDate settlement_;
    private com.google.protobuf.SingleFieldBuilder<
        com.lucera.lume.protobuf.treasury.inquiry.InquiryDate, com.lucera.lume.protobuf.treasury.inquiry.InquiryDate.Builder, com.lucera.lume.protobuf.treasury.inquiry.InquiryDateOrBuilder> settlementBuilder_;
    /**
     * <code>.treasury.InquiryDate settlement = 7;</code>
     * @return Whether the settlement field is set.
     */
    public boolean hasSettlement() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>.treasury.InquiryDate settlement = 7;</code>
     * @return The settlement.
     */
    public com.lucera.lume.protobuf.treasury.inquiry.InquiryDate getSettlement() {
      if (settlementBuilder_ == null) {
        return settlement_ == null ? com.lucera.lume.protobuf.treasury.inquiry.InquiryDate.getDefaultInstance() : settlement_;
      } else {
        return settlementBuilder_.getMessage();
      }
    }
    /**
     * <code>.treasury.InquiryDate settlement = 7;</code>
     */
    public Builder setSettlement(com.lucera.lume.protobuf.treasury.inquiry.InquiryDate value) {
      if (settlementBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        settlement_ = value;
      } else {
        settlementBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.treasury.InquiryDate settlement = 7;</code>
     */
    public Builder setSettlement(
        com.lucera.lume.protobuf.treasury.inquiry.InquiryDate.Builder builderForValue) {
      if (settlementBuilder_ == null) {
        settlement_ = builderForValue.build();
      } else {
        settlementBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.treasury.InquiryDate settlement = 7;</code>
     */
    public Builder mergeSettlement(com.lucera.lume.protobuf.treasury.inquiry.InquiryDate value) {
      if (settlementBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          settlement_ != null &&
          settlement_ != com.lucera.lume.protobuf.treasury.inquiry.InquiryDate.getDefaultInstance()) {
          getSettlementBuilder().mergeFrom(value);
        } else {
          settlement_ = value;
        }
      } else {
        settlementBuilder_.mergeFrom(value);
      }
      if (settlement_ != null) {
        bitField0_ |= 0x00000040;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.treasury.InquiryDate settlement = 7;</code>
     */
    public Builder clearSettlement() {
      bitField0_ = (bitField0_ & ~0x00000040);
      settlement_ = null;
      if (settlementBuilder_ != null) {
        settlementBuilder_.dispose();
        settlementBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.treasury.InquiryDate settlement = 7;</code>
     */
    public com.lucera.lume.protobuf.treasury.inquiry.InquiryDate.Builder getSettlementBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getSettlementFieldBuilder().getBuilder();
    }
    /**
     * <code>.treasury.InquiryDate settlement = 7;</code>
     */
    public com.lucera.lume.protobuf.treasury.inquiry.InquiryDateOrBuilder getSettlementOrBuilder() {
      if (settlementBuilder_ != null) {
        return settlementBuilder_.getMessageOrBuilder();
      } else {
        return settlement_ == null ?
            com.lucera.lume.protobuf.treasury.inquiry.InquiryDate.getDefaultInstance() : settlement_;
      }
    }
    /**
     * <code>.treasury.InquiryDate settlement = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.lucera.lume.protobuf.treasury.inquiry.InquiryDate, com.lucera.lume.protobuf.treasury.inquiry.InquiryDate.Builder, com.lucera.lume.protobuf.treasury.inquiry.InquiryDateOrBuilder> 
        getSettlementFieldBuilder() {
      if (settlementBuilder_ == null) {
        settlementBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.lucera.lume.protobuf.treasury.inquiry.InquiryDate, com.lucera.lume.protobuf.treasury.inquiry.InquiryDate.Builder, com.lucera.lume.protobuf.treasury.inquiry.InquiryDateOrBuilder>(
                getSettlement(),
                getParentForChildren(),
                isClean());
        settlement_ = null;
      }
      return settlementBuilder_;
    }

    private int price_ ;
    /**
     * <code>int32 price = 8;</code>
     * @return The price.
     */
    @java.lang.Override
    public int getPrice() {
      return price_;
    }
    /**
     * <code>int32 price = 8;</code>
     * @param value The price to set.
     * @return This builder for chaining.
     */
    public Builder setPrice(int value) {

      price_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>int32 price = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrice() {
      bitField0_ = (bitField0_ & ~0x00000080);
      price_ = 0;
      onChanged();
      return this;
    }

    private int originalPrice_ ;
    /**
     * <code>int32 originalPrice = 9;</code>
     * @return The originalPrice.
     */
    @java.lang.Override
    public int getOriginalPrice() {
      return originalPrice_;
    }
    /**
     * <code>int32 originalPrice = 9;</code>
     * @param value The originalPrice to set.
     * @return This builder for chaining.
     */
    public Builder setOriginalPrice(int value) {

      originalPrice_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>int32 originalPrice = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearOriginalPrice() {
      bitField0_ = (bitField0_ & ~0x00000100);
      originalPrice_ = 0;
      onChanged();
      return this;
    }

    private int cover_ ;
    /**
     * <code>int32 cover = 10;</code>
     * @return The cover.
     */
    @java.lang.Override
    public int getCover() {
      return cover_;
    }
    /**
     * <code>int32 cover = 10;</code>
     * @param value The cover to set.
     * @return This builder for chaining.
     */
    public Builder setCover(int value) {

      cover_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>int32 cover = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearCover() {
      bitField0_ = (bitField0_ & ~0x00000200);
      cover_ = 0;
      onChanged();
      return this;
    }

    private int yield_ ;
    /**
     * <code>int32 yield = 11;</code>
     * @return The yield.
     */
    @java.lang.Override
    public int getYield() {
      return yield_;
    }
    /**
     * <code>int32 yield = 11;</code>
     * @param value The yield to set.
     * @return This builder for chaining.
     */
    public Builder setYield(int value) {

      yield_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>int32 yield = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearYield() {
      bitField0_ = (bitField0_ & ~0x00000400);
      yield_ = 0;
      onChanged();
      return this;
    }

    private int position_ ;
    /**
     * <code>int32 position = 12;</code>
     * @return The position.
     */
    @java.lang.Override
    public int getPosition() {
      return position_;
    }
    /**
     * <code>int32 position = 12;</code>
     * @param value The position to set.
     * @return This builder for chaining.
     */
    public Builder setPosition(int value) {

      position_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>int32 position = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearPosition() {
      bitField0_ = (bitField0_ & ~0x00000800);
      position_ = 0;
      onChanged();
      return this;
    }

    private int numberOfDaysToSettle_ ;
    /**
     * <code>int32 numberOfDaysToSettle = 13;</code>
     * @return The numberOfDaysToSettle.
     */
    @java.lang.Override
    public int getNumberOfDaysToSettle() {
      return numberOfDaysToSettle_;
    }
    /**
     * <code>int32 numberOfDaysToSettle = 13;</code>
     * @param value The numberOfDaysToSettle to set.
     * @return This builder for chaining.
     */
    public Builder setNumberOfDaysToSettle(int value) {

      numberOfDaysToSettle_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>int32 numberOfDaysToSettle = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumberOfDaysToSettle() {
      bitField0_ = (bitField0_ & ~0x00001000);
      numberOfDaysToSettle_ = 0;
      onChanged();
      return this;
    }

    private boolean standardSettleDate_ ;
    /**
     * <code>bool standardSettleDate = 14;</code>
     * @return The standardSettleDate.
     */
    @java.lang.Override
    public boolean getStandardSettleDate() {
      return standardSettleDate_;
    }
    /**
     * <code>bool standardSettleDate = 14;</code>
     * @param value The standardSettleDate to set.
     * @return This builder for chaining.
     */
    public Builder setStandardSettleDate(boolean value) {

      standardSettleDate_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <code>bool standardSettleDate = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearStandardSettleDate() {
      bitField0_ = (bitField0_ & ~0x00002000);
      standardSettleDate_ = false;
      onChanged();
      return this;
    }

    private int risk_ ;
    /**
     * <code>int32 risk = 15;</code>
     * @return The risk.
     */
    @java.lang.Override
    public int getRisk() {
      return risk_;
    }
    /**
     * <code>int32 risk = 15;</code>
     * @param value The risk to set.
     * @return This builder for chaining.
     */
    public Builder setRisk(int value) {

      risk_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <code>int32 risk = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearRisk() {
      bitField0_ = (bitField0_ & ~0x00004000);
      risk_ = 0;
      onChanged();
      return this;
    }

    private int repoRate_ ;
    /**
     * <pre>
     * Only included if the quote has a non-standard settle date
     * </pre>
     *
     * <code>int32 repoRate = 16;</code>
     * @return The repoRate.
     */
    @java.lang.Override
    public int getRepoRate() {
      return repoRate_;
    }
    /**
     * <pre>
     * Only included if the quote has a non-standard settle date
     * </pre>
     *
     * <code>int32 repoRate = 16;</code>
     * @param value The repoRate to set.
     * @return This builder for chaining.
     */
    public Builder setRepoRate(int value) {

      repoRate_ = value;
      bitField0_ |= 0x00008000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Only included if the quote has a non-standard settle date
     * </pre>
     *
     * <code>int32 repoRate = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearRepoRate() {
      bitField0_ = (bitField0_ & ~0x00008000);
      repoRate_ = 0;
      onChanged();
      return this;
    }

    private int originalRepoRate_ ;
    /**
     * <code>int32 originalRepoRate = 17;</code>
     * @return The originalRepoRate.
     */
    @java.lang.Override
    public int getOriginalRepoRate() {
      return originalRepoRate_;
    }
    /**
     * <code>int32 originalRepoRate = 17;</code>
     * @param value The originalRepoRate to set.
     * @return This builder for chaining.
     */
    public Builder setOriginalRepoRate(int value) {

      originalRepoRate_ = value;
      bitField0_ |= 0x00010000;
      onChanged();
      return this;
    }
    /**
     * <code>int32 originalRepoRate = 17;</code>
     * @return This builder for chaining.
     */
    public Builder clearOriginalRepoRate() {
      bitField0_ = (bitField0_ & ~0x00010000);
      originalRepoRate_ = 0;
      onChanged();
      return this;
    }

    private int repoRatePrice_ ;
    /**
     * <code>int32 repoRatePrice = 18;</code>
     * @return The repoRatePrice.
     */
    @java.lang.Override
    public int getRepoRatePrice() {
      return repoRatePrice_;
    }
    /**
     * <code>int32 repoRatePrice = 18;</code>
     * @param value The repoRatePrice to set.
     * @return This builder for chaining.
     */
    public Builder setRepoRatePrice(int value) {

      repoRatePrice_ = value;
      bitField0_ |= 0x00020000;
      onChanged();
      return this;
    }
    /**
     * <code>int32 repoRatePrice = 18;</code>
     * @return This builder for chaining.
     */
    public Builder clearRepoRatePrice() {
      bitField0_ = (bitField0_ & ~0x00020000);
      repoRatePrice_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object sectorId_ = "";
    /**
     * <code>string sectorId = 19;</code>
     * @return The sectorId.
     */
    public java.lang.String getSectorId() {
      java.lang.Object ref = sectorId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sectorId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sectorId = 19;</code>
     * @return The bytes for sectorId.
     */
    public com.google.protobuf.ByteString
        getSectorIdBytes() {
      java.lang.Object ref = sectorId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sectorId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sectorId = 19;</code>
     * @param value The sectorId to set.
     * @return This builder for chaining.
     */
    public Builder setSectorId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sectorId_ = value;
      bitField0_ |= 0x00040000;
      onChanged();
      return this;
    }
    /**
     * <code>string sectorId = 19;</code>
     * @return This builder for chaining.
     */
    public Builder clearSectorId() {
      sectorId_ = getDefaultInstance().getSectorId();
      bitField0_ = (bitField0_ & ~0x00040000);
      onChanged();
      return this;
    }
    /**
     * <code>string sectorId = 19;</code>
     * @param value The bytes for sectorId to set.
     * @return This builder for chaining.
     */
    public Builder setSectorIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sectorId_ = value;
      bitField0_ |= 0x00040000;
      onChanged();
      return this;
    }

    private int originalRepoRatePrice_ ;
    /**
     * <code>int32 originalRepoRatePrice = 20;</code>
     * @return The originalRepoRatePrice.
     */
    @java.lang.Override
    public int getOriginalRepoRatePrice() {
      return originalRepoRatePrice_;
    }
    /**
     * <code>int32 originalRepoRatePrice = 20;</code>
     * @param value The originalRepoRatePrice to set.
     * @return This builder for chaining.
     */
    public Builder setOriginalRepoRatePrice(int value) {

      originalRepoRatePrice_ = value;
      bitField0_ |= 0x00080000;
      onChanged();
      return this;
    }
    /**
     * <code>int32 originalRepoRatePrice = 20;</code>
     * @return This builder for chaining.
     */
    public Builder clearOriginalRepoRatePrice() {
      bitField0_ = (bitField0_ & ~0x00080000);
      originalRepoRatePrice_ = 0;
      onChanged();
      return this;
    }

    private int repoUpdatedTimestamp_ ;
    /**
     * <code>int32 repoUpdatedTimestamp = 21;</code>
     * @return The repoUpdatedTimestamp.
     */
    @java.lang.Override
    public int getRepoUpdatedTimestamp() {
      return repoUpdatedTimestamp_;
    }
    /**
     * <code>int32 repoUpdatedTimestamp = 21;</code>
     * @param value The repoUpdatedTimestamp to set.
     * @return This builder for chaining.
     */
    public Builder setRepoUpdatedTimestamp(int value) {

      repoUpdatedTimestamp_ = value;
      bitField0_ |= 0x00100000;
      onChanged();
      return this;
    }
    /**
     * <code>int32 repoUpdatedTimestamp = 21;</code>
     * @return This builder for chaining.
     */
    public Builder clearRepoUpdatedTimestamp() {
      bitField0_ = (bitField0_ & ~0x00100000);
      repoUpdatedTimestamp_ = 0;
      onChanged();
      return this;
    }

    private com.lucera.lume.protobuf.treasury.inquiry.MarketData marketData_;
    private com.google.protobuf.SingleFieldBuilder<
        com.lucera.lume.protobuf.treasury.inquiry.MarketData, com.lucera.lume.protobuf.treasury.inquiry.MarketData.Builder, com.lucera.lume.protobuf.treasury.inquiry.MarketDataOrBuilder> marketDataBuilder_;
    /**
     * <code>.treasury.MarketData marketData = 22;</code>
     * @return Whether the marketData field is set.
     */
    public boolean hasMarketData() {
      return ((bitField0_ & 0x00200000) != 0);
    }
    /**
     * <code>.treasury.MarketData marketData = 22;</code>
     * @return The marketData.
     */
    public com.lucera.lume.protobuf.treasury.inquiry.MarketData getMarketData() {
      if (marketDataBuilder_ == null) {
        return marketData_ == null ? com.lucera.lume.protobuf.treasury.inquiry.MarketData.getDefaultInstance() : marketData_;
      } else {
        return marketDataBuilder_.getMessage();
      }
    }
    /**
     * <code>.treasury.MarketData marketData = 22;</code>
     */
    public Builder setMarketData(com.lucera.lume.protobuf.treasury.inquiry.MarketData value) {
      if (marketDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        marketData_ = value;
      } else {
        marketDataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00200000;
      onChanged();
      return this;
    }
    /**
     * <code>.treasury.MarketData marketData = 22;</code>
     */
    public Builder setMarketData(
        com.lucera.lume.protobuf.treasury.inquiry.MarketData.Builder builderForValue) {
      if (marketDataBuilder_ == null) {
        marketData_ = builderForValue.build();
      } else {
        marketDataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00200000;
      onChanged();
      return this;
    }
    /**
     * <code>.treasury.MarketData marketData = 22;</code>
     */
    public Builder mergeMarketData(com.lucera.lume.protobuf.treasury.inquiry.MarketData value) {
      if (marketDataBuilder_ == null) {
        if (((bitField0_ & 0x00200000) != 0) &&
          marketData_ != null &&
          marketData_ != com.lucera.lume.protobuf.treasury.inquiry.MarketData.getDefaultInstance()) {
          getMarketDataBuilder().mergeFrom(value);
        } else {
          marketData_ = value;
        }
      } else {
        marketDataBuilder_.mergeFrom(value);
      }
      if (marketData_ != null) {
        bitField0_ |= 0x00200000;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.treasury.MarketData marketData = 22;</code>
     */
    public Builder clearMarketData() {
      bitField0_ = (bitField0_ & ~0x00200000);
      marketData_ = null;
      if (marketDataBuilder_ != null) {
        marketDataBuilder_.dispose();
        marketDataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.treasury.MarketData marketData = 22;</code>
     */
    public com.lucera.lume.protobuf.treasury.inquiry.MarketData.Builder getMarketDataBuilder() {
      bitField0_ |= 0x00200000;
      onChanged();
      return getMarketDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.treasury.MarketData marketData = 22;</code>
     */
    public com.lucera.lume.protobuf.treasury.inquiry.MarketDataOrBuilder getMarketDataOrBuilder() {
      if (marketDataBuilder_ != null) {
        return marketDataBuilder_.getMessageOrBuilder();
      } else {
        return marketData_ == null ?
            com.lucera.lume.protobuf.treasury.inquiry.MarketData.getDefaultInstance() : marketData_;
      }
    }
    /**
     * <code>.treasury.MarketData marketData = 22;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.lucera.lume.protobuf.treasury.inquiry.MarketData, com.lucera.lume.protobuf.treasury.inquiry.MarketData.Builder, com.lucera.lume.protobuf.treasury.inquiry.MarketDataOrBuilder> 
        getMarketDataFieldBuilder() {
      if (marketDataBuilder_ == null) {
        marketDataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.lucera.lume.protobuf.treasury.inquiry.MarketData, com.lucera.lume.protobuf.treasury.inquiry.MarketData.Builder, com.lucera.lume.protobuf.treasury.inquiry.MarketDataOrBuilder>(
                getMarketData(),
                getParentForChildren(),
                isClean());
        marketData_ = null;
      }
      return marketDataBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:treasury.Leg)
  }

  // @@protoc_insertion_point(class_scope:treasury.Leg)
  private static final com.lucera.lume.protobuf.treasury.inquiry.Leg DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lucera.lume.protobuf.treasury.inquiry.Leg();
  }

  public static com.lucera.lume.protobuf.treasury.inquiry.Leg getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Leg>
      PARSER = new com.google.protobuf.AbstractParser<Leg>() {
    @java.lang.Override
    public Leg parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Leg> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Leg> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.lucera.lume.protobuf.treasury.inquiry.Leg getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

