// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/inquiry.proto
// Protobuf Java Version: 4.28.1

package com.lucera.lume.protobuf.treasury.inquiry;

/**
 * Protobuf type {@code treasury.MarketData}
 */
public final class MarketData extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:treasury.MarketData)
    MarketDataOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 1,
      /* suffix= */ "",
      MarketData.class.getName());
  }
  // Use MarketData.newBuilder() to construct.
  private MarketData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private MarketData() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lucera.lume.protobuf.treasury.inquiry.InquiryProtos.internal_static_treasury_MarketData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lucera.lume.protobuf.treasury.inquiry.InquiryProtos.internal_static_treasury_MarketData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lucera.lume.protobuf.treasury.inquiry.MarketData.class, com.lucera.lume.protobuf.treasury.inquiry.MarketData.Builder.class);
  }

  public static final int MAPXBIDPRICE_FIELD_NUMBER = 1;
  private int mapxBidPrice_ = 0;
  /**
   * <code>int32 mapxBidPrice = 1;</code>
   * @return The mapxBidPrice.
   */
  @java.lang.Override
  public int getMapxBidPrice() {
    return mapxBidPrice_;
  }

  public static final int MAPXBIDYIELD_FIELD_NUMBER = 2;
  private int mapxBidYield_ = 0;
  /**
   * <code>int32 mapxBidYield = 2;</code>
   * @return The mapxBidYield.
   */
  @java.lang.Override
  public int getMapxBidYield() {
    return mapxBidYield_;
  }

  public static final int MAPXOFFERPRICE_FIELD_NUMBER = 3;
  private int mapxOfferPrice_ = 0;
  /**
   * <code>int32 mapxOfferPrice = 3;</code>
   * @return The mapxOfferPrice.
   */
  @java.lang.Override
  public int getMapxOfferPrice() {
    return mapxOfferPrice_;
  }

  public static final int MAPXOFFERYIELD_FIELD_NUMBER = 4;
  private int mapxOfferYield_ = 0;
  /**
   * <code>int32 mapxOfferYield = 4;</code>
   * @return The mapxOfferYield.
   */
  @java.lang.Override
  public int getMapxOfferYield() {
    return mapxOfferYield_;
  }

  public static final int TWEBBIDPRICE_FIELD_NUMBER = 5;
  private int twebBidPrice_ = 0;
  /**
   * <code>int32 twebBidPrice = 5;</code>
   * @return The twebBidPrice.
   */
  @java.lang.Override
  public int getTwebBidPrice() {
    return twebBidPrice_;
  }

  public static final int TWEBBIDYIELD_FIELD_NUMBER = 6;
  private int twebBidYield_ = 0;
  /**
   * <code>int32 twebBidYield = 6;</code>
   * @return The twebBidYield.
   */
  @java.lang.Override
  public int getTwebBidYield() {
    return twebBidYield_;
  }

  public static final int TWEBOFFERPRICE_FIELD_NUMBER = 7;
  private int twebOfferPrice_ = 0;
  /**
   * <code>int32 twebOfferPrice = 7;</code>
   * @return The twebOfferPrice.
   */
  @java.lang.Override
  public int getTwebOfferPrice() {
    return twebOfferPrice_;
  }

  public static final int TWEBOFFERYIELD_FIELD_NUMBER = 8;
  private int twebOfferYield_ = 0;
  /**
   * <code>int32 twebOfferYield = 8;</code>
   * @return The twebOfferYield.
   */
  @java.lang.Override
  public int getTwebOfferYield() {
    return twebOfferYield_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (mapxBidPrice_ != 0) {
      output.writeInt32(1, mapxBidPrice_);
    }
    if (mapxBidYield_ != 0) {
      output.writeInt32(2, mapxBidYield_);
    }
    if (mapxOfferPrice_ != 0) {
      output.writeInt32(3, mapxOfferPrice_);
    }
    if (mapxOfferYield_ != 0) {
      output.writeInt32(4, mapxOfferYield_);
    }
    if (twebBidPrice_ != 0) {
      output.writeInt32(5, twebBidPrice_);
    }
    if (twebBidYield_ != 0) {
      output.writeInt32(6, twebBidYield_);
    }
    if (twebOfferPrice_ != 0) {
      output.writeInt32(7, twebOfferPrice_);
    }
    if (twebOfferYield_ != 0) {
      output.writeInt32(8, twebOfferYield_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (mapxBidPrice_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, mapxBidPrice_);
    }
    if (mapxBidYield_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, mapxBidYield_);
    }
    if (mapxOfferPrice_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, mapxOfferPrice_);
    }
    if (mapxOfferYield_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, mapxOfferYield_);
    }
    if (twebBidPrice_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, twebBidPrice_);
    }
    if (twebBidYield_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, twebBidYield_);
    }
    if (twebOfferPrice_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, twebOfferPrice_);
    }
    if (twebOfferYield_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, twebOfferYield_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.lucera.lume.protobuf.treasury.inquiry.MarketData)) {
      return super.equals(obj);
    }
    com.lucera.lume.protobuf.treasury.inquiry.MarketData other = (com.lucera.lume.protobuf.treasury.inquiry.MarketData) obj;

    if (getMapxBidPrice()
        != other.getMapxBidPrice()) return false;
    if (getMapxBidYield()
        != other.getMapxBidYield()) return false;
    if (getMapxOfferPrice()
        != other.getMapxOfferPrice()) return false;
    if (getMapxOfferYield()
        != other.getMapxOfferYield()) return false;
    if (getTwebBidPrice()
        != other.getTwebBidPrice()) return false;
    if (getTwebBidYield()
        != other.getTwebBidYield()) return false;
    if (getTwebOfferPrice()
        != other.getTwebOfferPrice()) return false;
    if (getTwebOfferYield()
        != other.getTwebOfferYield()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MAPXBIDPRICE_FIELD_NUMBER;
    hash = (53 * hash) + getMapxBidPrice();
    hash = (37 * hash) + MAPXBIDYIELD_FIELD_NUMBER;
    hash = (53 * hash) + getMapxBidYield();
    hash = (37 * hash) + MAPXOFFERPRICE_FIELD_NUMBER;
    hash = (53 * hash) + getMapxOfferPrice();
    hash = (37 * hash) + MAPXOFFERYIELD_FIELD_NUMBER;
    hash = (53 * hash) + getMapxOfferYield();
    hash = (37 * hash) + TWEBBIDPRICE_FIELD_NUMBER;
    hash = (53 * hash) + getTwebBidPrice();
    hash = (37 * hash) + TWEBBIDYIELD_FIELD_NUMBER;
    hash = (53 * hash) + getTwebBidYield();
    hash = (37 * hash) + TWEBOFFERPRICE_FIELD_NUMBER;
    hash = (53 * hash) + getTwebOfferPrice();
    hash = (37 * hash) + TWEBOFFERYIELD_FIELD_NUMBER;
    hash = (53 * hash) + getTwebOfferYield();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.lucera.lume.protobuf.treasury.inquiry.MarketData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lucera.lume.protobuf.treasury.inquiry.MarketData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lucera.lume.protobuf.treasury.inquiry.MarketData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lucera.lume.protobuf.treasury.inquiry.MarketData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lucera.lume.protobuf.treasury.inquiry.MarketData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lucera.lume.protobuf.treasury.inquiry.MarketData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lucera.lume.protobuf.treasury.inquiry.MarketData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.lucera.lume.protobuf.treasury.inquiry.MarketData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.lucera.lume.protobuf.treasury.inquiry.MarketData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.lucera.lume.protobuf.treasury.inquiry.MarketData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lucera.lume.protobuf.treasury.inquiry.MarketData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.lucera.lume.protobuf.treasury.inquiry.MarketData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lucera.lume.protobuf.treasury.inquiry.MarketData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code treasury.MarketData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:treasury.MarketData)
      com.lucera.lume.protobuf.treasury.inquiry.MarketDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lucera.lume.protobuf.treasury.inquiry.InquiryProtos.internal_static_treasury_MarketData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lucera.lume.protobuf.treasury.inquiry.InquiryProtos.internal_static_treasury_MarketData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lucera.lume.protobuf.treasury.inquiry.MarketData.class, com.lucera.lume.protobuf.treasury.inquiry.MarketData.Builder.class);
    }

    // Construct using com.lucera.lume.protobuf.treasury.inquiry.MarketData.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      mapxBidPrice_ = 0;
      mapxBidYield_ = 0;
      mapxOfferPrice_ = 0;
      mapxOfferYield_ = 0;
      twebBidPrice_ = 0;
      twebBidYield_ = 0;
      twebOfferPrice_ = 0;
      twebOfferYield_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lucera.lume.protobuf.treasury.inquiry.InquiryProtos.internal_static_treasury_MarketData_descriptor;
    }

    @java.lang.Override
    public com.lucera.lume.protobuf.treasury.inquiry.MarketData getDefaultInstanceForType() {
      return com.lucera.lume.protobuf.treasury.inquiry.MarketData.getDefaultInstance();
    }

    @java.lang.Override
    public com.lucera.lume.protobuf.treasury.inquiry.MarketData build() {
      com.lucera.lume.protobuf.treasury.inquiry.MarketData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.lucera.lume.protobuf.treasury.inquiry.MarketData buildPartial() {
      com.lucera.lume.protobuf.treasury.inquiry.MarketData result = new com.lucera.lume.protobuf.treasury.inquiry.MarketData(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.lucera.lume.protobuf.treasury.inquiry.MarketData result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.mapxBidPrice_ = mapxBidPrice_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.mapxBidYield_ = mapxBidYield_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.mapxOfferPrice_ = mapxOfferPrice_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.mapxOfferYield_ = mapxOfferYield_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.twebBidPrice_ = twebBidPrice_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.twebBidYield_ = twebBidYield_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.twebOfferPrice_ = twebOfferPrice_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.twebOfferYield_ = twebOfferYield_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lucera.lume.protobuf.treasury.inquiry.MarketData) {
        return mergeFrom((com.lucera.lume.protobuf.treasury.inquiry.MarketData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lucera.lume.protobuf.treasury.inquiry.MarketData other) {
      if (other == com.lucera.lume.protobuf.treasury.inquiry.MarketData.getDefaultInstance()) return this;
      if (other.getMapxBidPrice() != 0) {
        setMapxBidPrice(other.getMapxBidPrice());
      }
      if (other.getMapxBidYield() != 0) {
        setMapxBidYield(other.getMapxBidYield());
      }
      if (other.getMapxOfferPrice() != 0) {
        setMapxOfferPrice(other.getMapxOfferPrice());
      }
      if (other.getMapxOfferYield() != 0) {
        setMapxOfferYield(other.getMapxOfferYield());
      }
      if (other.getTwebBidPrice() != 0) {
        setTwebBidPrice(other.getTwebBidPrice());
      }
      if (other.getTwebBidYield() != 0) {
        setTwebBidYield(other.getTwebBidYield());
      }
      if (other.getTwebOfferPrice() != 0) {
        setTwebOfferPrice(other.getTwebOfferPrice());
      }
      if (other.getTwebOfferYield() != 0) {
        setTwebOfferYield(other.getTwebOfferYield());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              mapxBidPrice_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              mapxBidYield_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              mapxOfferPrice_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              mapxOfferYield_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              twebBidPrice_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              twebBidYield_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              twebOfferPrice_ = input.readInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              twebOfferYield_ = input.readInt32();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int mapxBidPrice_ ;
    /**
     * <code>int32 mapxBidPrice = 1;</code>
     * @return The mapxBidPrice.
     */
    @java.lang.Override
    public int getMapxBidPrice() {
      return mapxBidPrice_;
    }
    /**
     * <code>int32 mapxBidPrice = 1;</code>
     * @param value The mapxBidPrice to set.
     * @return This builder for chaining.
     */
    public Builder setMapxBidPrice(int value) {

      mapxBidPrice_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 mapxBidPrice = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMapxBidPrice() {
      bitField0_ = (bitField0_ & ~0x00000001);
      mapxBidPrice_ = 0;
      onChanged();
      return this;
    }

    private int mapxBidYield_ ;
    /**
     * <code>int32 mapxBidYield = 2;</code>
     * @return The mapxBidYield.
     */
    @java.lang.Override
    public int getMapxBidYield() {
      return mapxBidYield_;
    }
    /**
     * <code>int32 mapxBidYield = 2;</code>
     * @param value The mapxBidYield to set.
     * @return This builder for chaining.
     */
    public Builder setMapxBidYield(int value) {

      mapxBidYield_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 mapxBidYield = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMapxBidYield() {
      bitField0_ = (bitField0_ & ~0x00000002);
      mapxBidYield_ = 0;
      onChanged();
      return this;
    }

    private int mapxOfferPrice_ ;
    /**
     * <code>int32 mapxOfferPrice = 3;</code>
     * @return The mapxOfferPrice.
     */
    @java.lang.Override
    public int getMapxOfferPrice() {
      return mapxOfferPrice_;
    }
    /**
     * <code>int32 mapxOfferPrice = 3;</code>
     * @param value The mapxOfferPrice to set.
     * @return This builder for chaining.
     */
    public Builder setMapxOfferPrice(int value) {

      mapxOfferPrice_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 mapxOfferPrice = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMapxOfferPrice() {
      bitField0_ = (bitField0_ & ~0x00000004);
      mapxOfferPrice_ = 0;
      onChanged();
      return this;
    }

    private int mapxOfferYield_ ;
    /**
     * <code>int32 mapxOfferYield = 4;</code>
     * @return The mapxOfferYield.
     */
    @java.lang.Override
    public int getMapxOfferYield() {
      return mapxOfferYield_;
    }
    /**
     * <code>int32 mapxOfferYield = 4;</code>
     * @param value The mapxOfferYield to set.
     * @return This builder for chaining.
     */
    public Builder setMapxOfferYield(int value) {

      mapxOfferYield_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 mapxOfferYield = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMapxOfferYield() {
      bitField0_ = (bitField0_ & ~0x00000008);
      mapxOfferYield_ = 0;
      onChanged();
      return this;
    }

    private int twebBidPrice_ ;
    /**
     * <code>int32 twebBidPrice = 5;</code>
     * @return The twebBidPrice.
     */
    @java.lang.Override
    public int getTwebBidPrice() {
      return twebBidPrice_;
    }
    /**
     * <code>int32 twebBidPrice = 5;</code>
     * @param value The twebBidPrice to set.
     * @return This builder for chaining.
     */
    public Builder setTwebBidPrice(int value) {

      twebBidPrice_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 twebBidPrice = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTwebBidPrice() {
      bitField0_ = (bitField0_ & ~0x00000010);
      twebBidPrice_ = 0;
      onChanged();
      return this;
    }

    private int twebBidYield_ ;
    /**
     * <code>int32 twebBidYield = 6;</code>
     * @return The twebBidYield.
     */
    @java.lang.Override
    public int getTwebBidYield() {
      return twebBidYield_;
    }
    /**
     * <code>int32 twebBidYield = 6;</code>
     * @param value The twebBidYield to set.
     * @return This builder for chaining.
     */
    public Builder setTwebBidYield(int value) {

      twebBidYield_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 twebBidYield = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTwebBidYield() {
      bitField0_ = (bitField0_ & ~0x00000020);
      twebBidYield_ = 0;
      onChanged();
      return this;
    }

    private int twebOfferPrice_ ;
    /**
     * <code>int32 twebOfferPrice = 7;</code>
     * @return The twebOfferPrice.
     */
    @java.lang.Override
    public int getTwebOfferPrice() {
      return twebOfferPrice_;
    }
    /**
     * <code>int32 twebOfferPrice = 7;</code>
     * @param value The twebOfferPrice to set.
     * @return This builder for chaining.
     */
    public Builder setTwebOfferPrice(int value) {

      twebOfferPrice_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int32 twebOfferPrice = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTwebOfferPrice() {
      bitField0_ = (bitField0_ & ~0x00000040);
      twebOfferPrice_ = 0;
      onChanged();
      return this;
    }

    private int twebOfferYield_ ;
    /**
     * <code>int32 twebOfferYield = 8;</code>
     * @return The twebOfferYield.
     */
    @java.lang.Override
    public int getTwebOfferYield() {
      return twebOfferYield_;
    }
    /**
     * <code>int32 twebOfferYield = 8;</code>
     * @param value The twebOfferYield to set.
     * @return This builder for chaining.
     */
    public Builder setTwebOfferYield(int value) {

      twebOfferYield_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>int32 twebOfferYield = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearTwebOfferYield() {
      bitField0_ = (bitField0_ & ~0x00000080);
      twebOfferYield_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:treasury.MarketData)
  }

  // @@protoc_insertion_point(class_scope:treasury.MarketData)
  private static final com.lucera.lume.protobuf.treasury.inquiry.MarketData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lucera.lume.protobuf.treasury.inquiry.MarketData();
  }

  public static com.lucera.lume.protobuf.treasury.inquiry.MarketData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MarketData>
      PARSER = new com.google.protobuf.AbstractParser<MarketData>() {
    @java.lang.Override
    public MarketData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MarketData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MarketData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.lucera.lume.protobuf.treasury.inquiry.MarketData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

