// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/traderState.proto
// Protobuf Java Version: 4.28.1

package com.lucera.lume.protobuf.treasury.traderstate;

public interface TraderStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:treasury.TraderState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool active = 1;</code>
   * @return The active.
   */
  boolean getActive();
}
