// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/inquiry.proto
// Protobuf Java Version: 4.28.1

package com.lucera.lumemarkets.lumemarkets-protobuf.treasury.inquiry;

public interface LegOrBuilder extends
    // @@protoc_insertion_point(interface_extends:treasury.Leg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string legId = 1;</code>
   * @return The legId.
   */
  java.lang.String getLegId();
  /**
   * <code>string legId = 1;</code>
   * @return The bytes for legId.
   */
  com.google.protobuf.ByteString
      getLegIdBytes();

  /**
   * <code>bool isUnlocked = 2;</code>
   * @return The isUnlocked.
   */
  boolean getIsUnlocked();

  /**
   * <code>.treasury.Side side = 3;</code>
   * @return The enum numeric value on the wire for side.
   */
  int getSideValue();
  /**
   * <code>.treasury.Side side = 3;</code>
   * @return The side.
   */
  com.lucera.lumemarkets.lumemarkets-protobuf.treasury.inquiry.Side getSide();

  /**
   * <code>int32 quantity = 4;</code>
   * @return The quantity.
   */
  int getQuantity();

  /**
   * <code>string instrumentId = 5;</code>
   * @return The instrumentId.
   */
  java.lang.String getInstrumentId();
  /**
   * <code>string instrumentId = 5;</code>
   * @return The bytes for instrumentId.
   */
  com.google.protobuf.ByteString
      getInstrumentIdBytes();

  /**
   * <code>string marketSymbol = 6;</code>
   * @return The marketSymbol.
   */
  java.lang.String getMarketSymbol();
  /**
   * <code>string marketSymbol = 6;</code>
   * @return The bytes for marketSymbol.
   */
  com.google.protobuf.ByteString
      getMarketSymbolBytes();

  /**
   * <code>.treasury.InquiryDate settlement = 7;</code>
   * @return Whether the settlement field is set.
   */
  boolean hasSettlement();
  /**
   * <code>.treasury.InquiryDate settlement = 7;</code>
   * @return The settlement.
   */
  com.lucera.lumemarkets.lumemarkets-protobuf.treasury.inquiry.InquiryDate getSettlement();
  /**
   * <code>.treasury.InquiryDate settlement = 7;</code>
   */
  com.lucera.lumemarkets.lumemarkets-protobuf.treasury.inquiry.InquiryDateOrBuilder getSettlementOrBuilder();

  /**
   * <code>int32 price = 8;</code>
   * @return The price.
   */
  int getPrice();

  /**
   * <code>int32 originalPrice = 9;</code>
   * @return The originalPrice.
   */
  int getOriginalPrice();

  /**
   * <code>int32 cover = 10;</code>
   * @return The cover.
   */
  int getCover();

  /**
   * <code>int32 yield = 11;</code>
   * @return The yield.
   */
  int getYield();

  /**
   * <code>int32 position = 12;</code>
   * @return The position.
   */
  int getPosition();

  /**
   * <code>int32 numberOfDaysToSettle = 13;</code>
   * @return The numberOfDaysToSettle.
   */
  int getNumberOfDaysToSettle();

  /**
   * <code>bool standardSettleDate = 14;</code>
   * @return The standardSettleDate.
   */
  boolean getStandardSettleDate();

  /**
   * <code>int32 risk = 15;</code>
   * @return The risk.
   */
  int getRisk();

  /**
   * <pre>
   * Only included if the quote has a non-standard settle date
   * </pre>
   *
   * <code>int32 repoRate = 16;</code>
   * @return The repoRate.
   */
  int getRepoRate();

  /**
   * <code>int32 originalRepoRate = 17;</code>
   * @return The originalRepoRate.
   */
  int getOriginalRepoRate();

  /**
   * <code>int32 repoRatePrice = 18;</code>
   * @return The repoRatePrice.
   */
  int getRepoRatePrice();

  /**
   * <code>string sectorId = 19;</code>
   * @return The sectorId.
   */
  java.lang.String getSectorId();
  /**
   * <code>string sectorId = 19;</code>
   * @return The bytes for sectorId.
   */
  com.google.protobuf.ByteString
      getSectorIdBytes();

  /**
   * <code>int32 originalRepoRatePrice = 20;</code>
   * @return The originalRepoRatePrice.
   */
  int getOriginalRepoRatePrice();

  /**
   * <code>int32 repoUpdatedTimestamp = 21;</code>
   * @return The repoUpdatedTimestamp.
   */
  int getRepoUpdatedTimestamp();

  /**
   * <code>.treasury.MarketData marketData = 22;</code>
   * @return Whether the marketData field is set.
   */
  boolean hasMarketData();
  /**
   * <code>.treasury.MarketData marketData = 22;</code>
   * @return The marketData.
   */
  com.lucera.lumemarkets.lumemarkets-protobuf.treasury.inquiry.MarketData getMarketData();
  /**
   * <code>.treasury.MarketData marketData = 22;</code>
   */
  com.lucera.lumemarkets.lumemarkets-protobuf.treasury.inquiry.MarketDataOrBuilder getMarketDataOrBuilder();
}
