// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/inquiry.proto
// Protobuf Java Version: 4.28.1

package com.lucera.lumemarkets.lumemarkets-protobuf.treasury.inquiry;

/**
 * Protobuf enum {@code treasury.Side}
 */
public enum Side
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>SELL = 0;</code>
   */
  SELL(0),
  /**
   * <code>BUY = 1;</code>
   */
  BUY(1),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 1,
      /* suffix= */ "",
      Side.class.getName());
  }
  /**
   * <code>SELL = 0;</code>
   */
  public static final int SELL_VALUE = 0;
  /**
   * <code>BUY = 1;</code>
   */
  public static final int BUY_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Side valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Side forNumber(int value) {
    switch (value) {
      case 0: return SELL;
      case 1: return BUY;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Side>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Side> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Side>() {
          public Side findValueByNumber(int number) {
            return Side.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.lucera.lumemarkets.lumemarkets-protobuf.treasury.inquiry.InquiryProtos.getDescriptor().getEnumTypes().get(1);
  }

  private static final Side[] VALUES = values();

  public static Side valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Side(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:treasury.Side)
}

